version: '3.8'

services:
  # Spring Boot Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: backend-docker
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    restart: unless-stopped
    networks:
      - weather-app-network

  # Angular Frontend Service
  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend-docker
    ports:
      - "4201:80"
    depends_on:
      - backend
    networks:
      - weather-app-network

  # Optional: Monitoring Service
  monitoring:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - weather-app-network

networks:
  weather-app-network:
    driver: bridge